version: "3"
services:
  engecopi:
    image: tomcat:8
    container_name: eng_contrato
    ports:
      - "8029:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
    volumes:
      - ./build/libs/engContratos.war:/usr/local/tomcat/webapps/eng_contratos.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_contrato:
        ipv4_address: 172.129.1.1
networks:
  rede_contrato:
    ipam:
      driver: default
      config:
        - subnet: 172.129.0.0/16
